services:
  app:
    container_name: app
    restart: always
    build: ./app
    environment:
      - MONGO_ADDR=mongodb://admin:admin@mongodb:27017
      - ES_ADDR=http://elasticsearch:9200
    networks:
      - projectr_nw
    ports:
      - "5000:5000"

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    networks:
      - projectr_nw
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    networks:
      - projectr_nw
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data

  nginx:
    image: nginx:stable
    restart: always
    container_name: nginx
    networks:
      - projectr_nw
    volumes:
      - ${PWD}/config/nginx/conf.d:/etc/nginx/conf.d
      - ${PWD}/config/nginx/access.conf:/etc/nginx/access.conf
      - ${PWD}/log/nginx:/var/log/nginx
    ports:
      - 8080:80 # app port

  telegraf:
    image: telegraf
    container_name: telegraf
    user: root
    entrypoint: "telegraf"
    restart: always
    networks:
      - projectr_nw
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8125:8125"

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    networks:
      - projectr_nw
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.36.2
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - projectr_nw
    ports:
      - 9090:9090
    depends_on:
      - telegraf

volumes:
  grafana_data: {}
  prometheus_data: {}
  mongodb_data: {}
  es_data: {}

networks:
  projectr_nw:
    name: projectr_nw
