jobs:
  - type: http
    args:
      dynamic: true
      request:
        method: POST
        path: http://localhost:8080/
        headers:
          Content-Type: application/json
        body: '{ "key": "{{random_alphanum 10}}", "value": "{{random_alphanum 10}}", "db":"mongo"}'
  - type: http
    args:
      dynamic: true
      request:
        method: POST
        path: http://localhost:8080/
        headers:
          Content-Type: application/json
        body: '{ "key": "{{random_alphanum 10}}", "value": "{{random_alphanum 10}}", "db":"elastic"}'
